name: Testing context, properties and variables

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
    global_env_var: This variable is declared at worflow level

jobs:
    exploring_contexts:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v5
            - name: run maven clean
              run: "mvn clean"
            - name: print github attributes
              run: echo ${{github.repository}} and ${{github.actor}}
            - name: printing contexts
              run: |

                 echo '${{toJson(github)}}'
                 echo '${{toJson(runner)}}'
                 echo '${{toJson(env)}}'
            - name: printing global env var
              run: echo ${{env.global_env_var}}

    exploring_env_variables:
        runs-on: ubuntu-latest
        env:
            job_level_env: This is declared at job level
        steps:
            - name: Printing global var
              env:
                    step_env: This is declared at step level
              run: |

                echo ${{env.global_env_var}}
                echo ${{env.step_env}}
            
            - name: Printing job level var
              run: echo ${{ env.job_level_env }}
            





